### ISSUE TITLE
why the hell is axios a dependency

### ISSUE THREAD

**Issue by xorraxraxret** [rhettlunn/is-odd-ai#15]

**Comment by rhettlunn** [comment]
xorraxraxret,

Your account has been blocked from contributing to is-odd-ai due to recent abusive comments directed at other community members. This behavior violates our project's standards for respectful and constructive communication.

We encourage you to reflect on this and consider how you can engage more positively in open-source communities. If you wish to contribute in the future, please ensure your interactions align with our community guidelines.

**Comment by xorraxraxret** [comment]
> xorraxraxret,
> 
> Your account has been blocked from contributing to is-odd-ai due to recent abusive comments directed at other community members. This behavior violates our project's standards for respectful and constructive communication.
> 
> We encourage you to reflect on this and consider how you can engage more positively in open-source communities. If you wish to contribute in the future, please ensure your interactions align with our community guidelines.

good thing i wasnt contributing
